- name: Provision ECS resources
  hosts: localhost
  gather_facts: false
  collections:
    - community.aws

  tasks:
    - name: Ensure ECS cluster exists
      ecs_cluster:
        name: petClinicCluster
        state: present

    - name: Register ECS task definition
      community.aws.ecs_taskdefinition:
        family: my-task-family
        execution_role_arn: "arn:aws:iam::339712705537:role/ecsTaskExecutionRole"
        network_mode: awsvpc
        cpu: '256'
        memory: '512'
        launch_type: "FARGATE"
        containers:
          - name: pet-clinic
            image: 339712705537.dkr.ecr.eu-north-1.amazonaws.com/pet-clinic:latest
            cpu: 256
            memory: 512
            essential: true
            portMappings:
              - containerPort: 8080
            logConfiguration:
              logDriver: awslogs
              options:
                awslogs-group: my-log-group
                awslogs-region: eu-north-1
                awslogs-stream-prefix: my-app
        state: present

    - name: Ensure service exists
      community.aws.ecs_service:
        name: my-service
        cluster: petClinicCluster
        task_definition: my-task-family
        desired_count: 1
        launch_type: "FARGATE"
        state: present
        network_configuration:
          subnets:
            - subnet-09d7a2c4366d24b53
          security_groups:
            - sg-077c4ad5a1e723026
          assign_public_ip: true
##
